### ISSUE TITLE
Add easy taxi

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/uber-cities#11]
http://www.easytaxi.com/cities/

**Comment by machour** [comment]
I'd like to handle this one if it's okay for you.

They don't see to have a page per city like other providers.
Would something like 
```json
{
  "cities": [
    {
      "name": "Buenos Aires",
      "link": "/cities/#city"
    },
    ...
```
be good enough?

**Comment by SaraVieira** [comment]
Sure ! That would be awesome 🎉

**Comment by machour** [comment]
Perfect! Just waiting for feedback on #6 before opening a new PR (to avoid a horrible conflict 😄)

**Comment by SaraVieira** [comment]
Merged ! Thank you so much 😄
