### ISSUE TITLE
Search enhancements

### ISSUE THREAD

**Issue by machour** [SaraVieira/uber-cities#12]
Currently, if I type a single letter and hit enter, the app will always respond "Yes" as the letter is included in a city somewhere.

Maybe something like http://fusejs.io/ could help with this one and #10

**Comment by machour** [comment]
Also, displaying the matched city in the result could help the user making sure the result is accurate :)

**Comment by SaraVieira** [comment]
Fuse js sounds awesome and I think I will go with that mainly because of naming conventions in apps being different :(

I stared by equaling them but then I had issues where Porto was called Oporto in some other app and new York was new York city :(

But I think fuse is an awesome middleterm for that :)

**Comment by Haroenv** [comment]
Hey! I work at Algolia, what do you think of adding the data by canonical name, and use an input like [Places](https://community.algolia.com/places). I can help setting it up and a synchronisation process if needed!

**Comment by SaraVieira** [comment]
Hey @Haroenv ,

What do you mean by canonical name ? Because this looks perfect

**Comment by Haroenv** [comment]
Basically we can pick an id (I’m sure there’s official standard, cc @raphi) for each city and then some synonyms or different attributes for that record, different languages and a geo location, and then that record can have the rider info in there

**Comment by SaraVieira** [comment]
Mhmm, I will look into this tomorrow because this would fix all the problems right now

And the json is now set to be updated so it will never delete the old id's

**Comment by machour** [comment]
_whispers: "introduce the country notion while you're at it"_ 😄

**Comment by raphi** [comment]
Yes you can use the ID or a combination of attributes for it. Just keep in mind that IDs are stable, but they are unique.

_you can get a country list via Places as well^^_

**Comment by SaraVieira** [comment]
I introduced algolia search in latest build: https://build-pmsovolbme.now.sh

If your 	query is smaller than 3 words it will always return no in any other case it will ask you what city you meant :)

I'm gonna close this and y'all feel free to reopen if anything surfaces
