### ISSUE TITLE
Incorrect Lyft result (London, UK)

### ISSUE THREAD

**Issue by johnrees** [SaraVieira/uber-cities#25]
I like this tool. I did notice a little bug though, we don't have Lyft in London but it's a [positive result](https://isthereuber.in/london).

I guess it's related to checking if the query [includes the string](
https://github.com/SaraVieira/uber-cities/blob/master/src/routes/city/index.js#L82) rather than matching it exactly? i.e. "New London" is a Lyft city, so a term like [Londo](https://isthereuber.in/londo) is also a positive match.

**Comment by SaraVieira** [comment]
I'm going to start working with algolia to match every city to a code and that way that won't happen 😀

It will be super accurate 👊

**Comment by SaraVieira** [comment]
Fixed in latest version: https://build-pmsovolbme.now.sh
