### ISSUE TITLE
Cabify does not appear in the Sao Paulo city results on production

### ISSUE THREAD

**Issue by tcelestino** [SaraVieira/uber-cities#28]
On production, when I do a search for Sao Paulo (or São Paulo), only show me easytaxi as an option. I've thought this is a bug and I forked the project to debug it. But, when I've ran the application locally there is cabify in the results.

I did the print screen that show the difference:

**local**
![image](https://user-images.githubusercontent.com/190265/35470633-31029714-0334-11e8-8a4c-892b8387169e.png)

**production**
![image](https://user-images.githubusercontent.com/190265/35470661-a0daa892-0334-11e8-9179-6051342687fc.png)

I don't know, but I think it seem need to deploy that update the last version on production. 

PS.: congrats for project. ;)

**Comment by SaraVieira** [comment]
Thanks ! I already updated: https://isthereuber.in/sao-paulo.

Thanks for letting me know :)
