### ISSUE TITLE
Verify details

### ISSUE THREAD

**Issue by jouni-kantola** [SaraVieira/uber-cities#45]
I ❤️ the idea, @SaraVieira!

I read about the use-case you were going for, that you wanted to know if a specific you were traveling to had Uber or any service like it.

Wouldn't you want to know the details you had were verified by a local (or the company)? I personally would probably be googling afterwards anyways to verify the information I got is correct and up to date. Maybe I'm paranoid, but I'd really appreciate some kind of _Last Verified: [date]_ label on routes/cities that have tested.

Great work!

**Comment by SaraVieira** [comment]
Hey !

I can add a link to the uber page on it so you know if the page still exists it's still there

**Comment by jouni-kantola** [comment]
Yeah, that's cool. Do you see the other taxi services as fallbacks or as an important part of the site as Uber? I figured if they are as important, then their matching links would be great to have close at hand as well.

**Comment by SaraVieira** [comment]
Those already have a PR to add the app store links so you can download the app because most of them don't have links for each city and some don't even have this information :(

**Comment by jouni-kantola** [comment]
I guess isthereuber.in will be the go-to source then 😄 Even more speaks for your product idea. Let's start with the link. In almost all cases I guess that will suffice.

**Comment by SaraVieira** [comment]
The PR got merged :D  

we now have app store links and I will add the uber links tomorrow :)

**Comment by SaraVieira** [comment]
Hey !


I have added the links when you click on yes it takes you to the uber website.

Can this be closed ?

**Comment by jouni-kantola** [comment]
Nice 👍 
Closing!
