### ISSUE TITLE
Inconsistent

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/uber-cities#47]
Hey, it would be great to recognize "Lisboa" as "Lisbon". Also, Barcelona has Uber. Lisbon has Mytaxi and chauffeur privé

**Comment by Ma7eer** [comment]
Hey I am a new developer and would love to tackle this! Can I start on it?

**Comment by Ma7eer** [comment]
No worries! I am observing this project for now (super interesting to me) so when I find something I will go for it. Thank you
