### ISSUE TITLE
Adding Careem to the Single Folder

### ISSUE THREAD

**Issue by Ma7eer** [SaraVieira/uber-cities#49]
Hello was wondering if you think its a good idea to add Careem? it is widely used all over the middle east where I am from. If you think its a good idea I can tackle this one.

**Comment by SaraVieira** [comment]
Hey!

Yes, that would be amazing!

**Comment by SaraVieira** [comment]
All cities can be found here: https://www.careem.com/en-ae/cities/ :D

**Comment by Ma7eer** [comment]
Quick question! From where can I get the place_id?? I noticed that each object in the filed that are in the single folder have it? Wasn’t sure where to get that

**Comment by SaraVieira** [comment]
If you pass your array of cities with just name and company through this function https://github.com/SaraVieira/uber-cities/blob/master/data/getData.js#L18 it will go to the google maps api, fill in all the data and create a new file with it.

So you can call like:

```js
leMap([{city: 'Doha', company: 'careem'}], 'careem')
```

And it will create a new file in the single folder

Let me know any issues

**Comment by Ma7eer** [comment]
Makes sense Thank  will work on it now!

**Comment by SaraVieira** [comment]
Awesome!!

**Comment by SaraVieira** [comment]
PR MERGED :D
