### ISSUE TITLE
Cropped confettis on Android

### ISSUE THREAD

**Issue by machour** [SaraVieira/uber-cities#5]
Hi here,

Testing the app on my OnePlus 3T, I noticed that confettis are constrained to a portion of the screen, while they go all the way down on desktop:

![screenshot_20180115-100250](https://user-images.githubusercontent.com/304450/34934705-b83cb03c-f9db-11e7-98a3-1e2db106d2b2.jpg)

**Comment by SaraVieira** [comment]
Hello!

I noticed this on my phone yesterday too, I'll get on this today :)

**Comment by SaraVieira** [comment]
This has been fixed by removing react size me and added window.innerHeight

No need to make it fancy sometimes -.-
