### ISSUE TITLE
Add Yandex Taxi

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/uber-cities#51]
Have no idea where the fuck they operate

**Comment by joaoqalves** [comment]
I've found some cities but unless we know someone that writes Cyrillic and understands Russian-like languages, we're doomed :) Cities where I could find that Yandex operates:

- Moscow (RU)
- Saint Petersburg (RU)
- Kazan (RU)
- Novosibirsk (RU)
- Yekaterinburg (RU)
- Nizhny Novgorod (RU)
- Ufa (RU)
- Minsk (BY)
- Tallin (EE)
- Riga (LV)
- Chisinau (MD)
- Almaty (KZ)
- Yerevan (AM)
- Vanadzor (AM)
- Gyumri (AM)
- Tbilisi (GE)
- Tashkent (UZ)
- Belgrade (RS)

All of these were manually crawled from Wikipedia, with Google translate help. Do you think it's worth to put them?

**Comment by SaraVieira** [comment]
I think so mostly because I say when you search for russia thats it's advised to use yandex taxi :(

Ill create docs on how to add new things and paste it here :)

The countries and all of that uses the GoogleMaps api so I just need the name

**Comment by SaraVieira** [comment]
@joaoqalves I made a small explanation on how to add a provider here: https://github.com/SaraVieira/uber-cities#i-want-to-add-a-provider

Let me know if you have any issues :)

**Comment by SaraVieira** [comment]
Also the apps:

ios: https://itunes.apple.com/us/app/yandex-taxi/id472650686
android: https://play.google.com/store/apps/details?id=ru.yandex.taxi

**Comment by SaraVieira** [comment]
Published :D
