### ISSUE TITLE
Guanajuato shows up in search  has a city in Ghana 

### ISSUE THREAD

**Issue by netEmmanuel** [SaraVieira/uber-cities#52]
Guanajuato shows up as a city in Ghana where Uber is available. This is incorrect

**Comment by SaraVieira** [comment]
It's a city in Mexico and in Ghana and that's why it shows up

<img width="564" alt="screenshot 2018-11-25 at 17 42 21" src="https://user-images.githubusercontent.com/1051509/48981720-86817280-f0d9-11e8-8677-653f1b03c409.png">

**Comment by SaraVieira** [comment]
I added the flag of the country in the result to avoid this: https://isthereuber.in/Guanajuato

**Comment by netEmmanuel** [comment]
That's interesting. Guanajuato is definitely not a city in Ghana.
