### ISSUE TITLE
Keyboard moves Algolia logo and text 

### ISSUE THREAD

**Issue by donovantc** [SaraVieira/uber-cities#57]
**What is the current behavior?**
Focusing on the search input causes the keyboard to show. This pushes the Algolia logo and text from the bottom of the page, which overlaps the search input.

![saghxqkp 1](https://user-images.githubusercontent.com/1227748/48984286-1df6bd80-f0fa-11e8-9eff-53b97cb5cb73.jpg)

**Device/OS/Browser**
ZTE Axon 7 / android 8.0 / chrome mobile

@SaraVieira the link in issue #53 is not working. Also I added some more details here, so I suggest closing #53

**Comment by SaraVieira** [comment]
Closed and thank you for creating the issue :)
