### ISSUE TITLE
Add heetch

### ISSUE THREAD

**Issue by SaraVieira** [SaraVieira/uber-cities#68]
https://www.heetch.com/fr/cities/

ios: https://itunes.apple.com/fr/app/heetch-enjoy-your-night-out/id693137280?mt=8
android: https://play.google.com/store/apps/details?id=com.heetch&hl=fr

**Comment by Ma7eer** [comment]
I am willing to do this if no one has taken it on!

**Comment by SaraVieira** [comment]
Sure! That would be awesome :)
