### ISSUE TITLE
iOS 12 Siri Shortcut

### ISSUE THREAD

**Issue by zhigang1992** [SaraVieira/uber-cities#79]
https://www.icloud.com/shortcuts/7567010b47ec4ffa806a3f71eac621cb

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1057756/50215072-e90a1d80-03bc-11e9-9b04-727024947209.gif)

But I'm not able to get the AppStore link since appstore.json it's not actually somewhere accessible online.

**Comment by SaraVieira** [comment]
Hey !

This is amazing :D

Is this what you are looking for? https://github.com/SaraVieira/uber-cities/blob/master/src/utils/appStores.js#L10

Want me to make it a json file ?

**Comment by SaraVieira** [comment]
Ofc.

Made it and you can use this link to get it with correct headers from GH: https://raw.githack.com/SaraVieira/uber-cities/master/src/utils/app-stores-links.json

If I update master it updates here too 

Is this what you need ? :)

**Comment by zhigang1992** [comment]
Perfect!

**Comment by SaraVieira** [comment]
I will leave this open untill you publish the updated version, cool ? :)

**Comment by SaraVieira** [comment]
Also if you want the logo here it is:

![logo-uber-cites](https://user-images.githubusercontent.com/1051509/50227564-e8ae5a00-039d-11e9-8067-7ce3c0746d14.png)
![one](https://user-images.githubusercontent.com/1051509/50227571-ec41e100-039d-11e9-832a-a508cc2d39cc.png)


Use it as you please :)

**Comment by zhigang1992** [comment]
Done, https://www.icloud.com/shortcuts/1ce5095b54034b5c986bfbf00c062df5
Unfortunately, we can't customize iOS 12 shortcut's icon only the home screen icon.

Here is how it looks like
![image](https://user-images.githubusercontent.com/1057756/50279930-1a9aeb80-0486-11e9-98eb-47a7630c612d.png)

**Comment by SaraVieira** [comment]
OMG THIS IS AWESOME! THANK YOU!
